[package]
name = "bookscanner-server"
version = "0.1.0"
authors = ["Luciano Nooijen <luciano@bytecode.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.7"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
rocket_contrib = "0.4.7"
